---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: latest
  - name: enable service httpd and ensure it is not masked
    systemd:
      name: httpd
      state: started
      enabled: yes
